FROM alpine:latest

RUN apk update && apk add squid iptables

COPY squid.conf /etc/squid/squid.conf
COPY entrypoint.sh /usr/local/bin/proxy-entrypoint.sh

RUN squid -z || true
RUN chmod +x /usr/local/bin/proxy-entrypoint.sh

CMD ["/usr/local/bin/proxy-entrypoint.sh"]