FROM alpine:latest

# Εγκατάσταση απαραίτητων εργαλείων (iproute2 περιέχει το tc)
RUN apk add --no-cache iproute2 iputils bash

WORKDIR /scripts

# Αντιγραφή του script και δικαιώματα εκτέλεσης
COPY tc_rules.sh .
RUN chmod +x tc_rules.sh

# Εκτέλεση του script
CMD ["./tc_rules.sh"]