FROM alpine:latest

RUN apk add --no-cache iptables iproute2 tcpdump

WORKDIR /scripts

COPY firewall_rules.sh .
RUN chmod +x firewall_rules.sh

CMD ["/bin/sh", "-c", "./firewall_rules.sh && tail -f /dev/null"]